name: Mothd Docker build
on: [push]

jobs:
  build-mothd:
    name: Build mothd
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v1
      - name: Build mothd
        run: docker build .
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: dirtbags/moth/moth
          tag_with_ref: true
