name: Publish
on:
  push:
    tags: 
      -  'v*' # Only versioned tags

jobs:
  publish:
    name: Publish Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v1

      - name: Push moth to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          target: moth
          file: build/package/Containerfile
          registry: docker.pkg.github.com
          repository: dirtbags/moth/moth
          tag_with_ref: true
          
      - name: Push moth-devel to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          target: moth-devel
          file: build/package/Containerfile
          registry: docker.pkg.github.com
          repository: dirtbags/moth/moth-devel
          tag_with_ref: true
          
      - name: Push moth to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: neale
          password: ${{ secrets.DOCKER_TOKEN }}
          target: moth
          file: build/packages/Containerfile
          repository: dirtbags/moth
          tag_with_ref: true

      - name: Push moth-devel to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: neale
          password: ${{ secrets.DOCKER_TOKEN }}
          target: moth-devel
          file: build/packages/Containerfile
          repository: dirtbags/moth-devel
          tag_with_ref: true
