name: Tests
on: [push]

jobs:
  test-mothd:
    name: Test mothd
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13            
      - name: Retrieve code
        uses: actions/checkout@v1
      - name: Test
        run: go test ./...

  publish:
    name: Publish latest build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: neale
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push moth image
        uses: docker/build-push-action@v2
        with:
          target: moth
          file: build/package/Containerfile
          tags: 
            - dirtbags/moth:latest
            - docker.pkg.github.com/dirtbags/moth/moth:latest

      - name: Build and push moth-devel image
        uses: docker/build-push-action@v2
        with:
          target: moth
          file: build/package/Containerfile
          tags: |
            dirtbags/moth-devel:latest
            docker.pkg.github.com/dirtbags/moth/moth-devel:latest
